```plantuml

@startuml
scale 600 width

[*] -> START
START: Show Title
START --> START_GAME : Button Press
START_GAME: Reset Sequence
START_GAME: Select 1st Element
START_GAME -down-> PLAY_SEQUENCE
PLAY_SEQUENCE: Play Sequence
PLAY_SEQUENCE -down-> COMPARE_SEQUENCE
COMPARE_SEQUENCE: Reset Timer, Compare motion input across sequence in a loop
COMPARE_SEQUENCE --> GAME_OVER : Input did not match / \nTime Expired
GAME_OVER: Show Score
COMPARE_SEQUENCE --> INCREMENT_SEQUENCE_SIZE: matched last index  
GAME_OVER-> START_GAME: Button Press
INCREMENT_SEQUENCE_SIZE: Select next random Direction
INCREMENT_SEQUENCE_SIZE: increment sequence size
INCREMENT_SEQUENCE_SIZE-> PLAY_SEQUENCE
@end_uml

